http_server:
    port: 8080
    host: ""
logger:
    level: "info"
    path: "./log/log.log"
    max_bytes: 10e7
postgres:
    host: "postgres"
    migrations: "file://internal/infrastructure/database/migrations"
    port: 5432
    user: "postgres"
    password: "postgres"
    dbname: "postgres"
    sslmode: "disable"
kafka:
    topic: "orders"
    num_partitions: 10
    max_bytes: 10e6
    replication_factor: 1
    brokers:
        - "kafka:29092"
memory_cache:
#   Max count objects in cache.
    capacity: 10e6

new_relic:
    app_name: "order-service"
    license: "Apache-2.0"
sentry:
    dsn: ""